name: Build and Test

on:
  # Runs on pushes targeting the default branch
  pull_request:

jobs:
  # Single deploy job since we're just deploying
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
